/*
Navicat PGSQL Data Transfer

Source Server         : 172.16.2.192
Source Server Version : 90405
Source Host           : 172.16.2.192:5432
Source Database       : dangxi
Source Schema         : public

Target Server Type    : PGSQL
Target Server Version : 90405
File Encoding         : 65001

Date: 2016-06-29 08:22:16
*/


-- ----------------------------
-- Sequence structure for advert_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."advert_seq";
CREATE SEQUENCE "public"."advert_seq"
 INCREMENT 1
 MINVALUE 1
 MAXVALUE 9223372036854775807
 START 20
 CACHE 1;
SELECT setval('"public"."advert_seq"', 20, true);

-- ----------------------------
-- Sequence structure for authorised_user_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."authorised_user_seq";
CREATE SEQUENCE "public"."authorised_user_seq"
 INCREMENT 1
 MINVALUE 1
 MAXVALUE 9223372036854775807
 START 298
 CACHE 1;
SELECT setval('"public"."authorised_user_seq"', 298, true);

-- ----------------------------
-- Sequence structure for fund_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."fund_seq";
CREATE SEQUENCE "public"."fund_seq"
 INCREMENT 1
 MINVALUE 1
 MAXVALUE 9223372036854775807
 START 20
 CACHE 1;
SELECT setval('"public"."fund_seq"', 20, true);

-- ----------------------------
-- Sequence structure for fund_type_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."fund_type_seq";
CREATE SEQUENCE "public"."fund_type_seq"
 INCREMENT 1
 MINVALUE 1
 MAXVALUE 9223372036854775807
 START 20
 CACHE 1;
SELECT setval('"public"."fund_type_seq"', 20, true);

-- ----------------------------
-- Sequence structure for info_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."info_seq";
CREATE SEQUENCE "public"."info_seq"
 INCREMENT 1
 MINVALUE 1
 MAXVALUE 9223372036854775807
 START 80
 CACHE 1;
SELECT setval('"public"."info_seq"', 80, true);

-- ----------------------------
-- Sequence structure for info_type_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."info_type_seq";
CREATE SEQUENCE "public"."info_type_seq"
 INCREMENT 1
 MINVALUE 1
 MAXVALUE 9223372036854775807
 START 20
 CACHE 1;
SELECT setval('"public"."info_type_seq"', 20, true);

-- ----------------------------
-- Sequence structure for security_role_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."security_role_seq";
CREATE SEQUENCE "public"."security_role_seq"
 INCREMENT 1
 MINVALUE 1
 MAXVALUE 9223372036854775807
 START 127
 CACHE 1;
SELECT setval('"public"."security_role_seq"', 127, true);

-- ----------------------------
-- Sequence structure for user_permission_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."user_permission_seq";
CREATE SEQUENCE "public"."user_permission_seq"
 INCREMENT 1
 MINVALUE 1
 MAXVALUE 9223372036854775807
 START 1148
 CACHE 1;
SELECT setval('"public"."user_permission_seq"', 1148, true);

-- ----------------------------
-- Table structure for advert
-- ----------------------------
DROP TABLE IF EXISTS "public"."advert";
CREATE TABLE "public"."advert" (
"id" int8 DEFAULT nextval('advert_seq'::regclass) NOT NULL,
"code" varchar(255) COLLATE "default",
"name" varchar(255) COLLATE "default",
"picture" text COLLATE "default",
"url" varchar(255) COLLATE "default"
)
WITH (OIDS=FALSE)

;

-- ----------------------------
-- Records of advert
-- ----------------------------
INSERT INTO "public"."advert" VALUES ('1', 'test', 'test', null, null);

-- ----------------------------
-- Table structure for authorised_user
-- ----------------------------
DROP TABLE IF EXISTS "public"."authorised_user";
CREATE TABLE "public"."authorised_user" (
"id" int8 DEFAULT nextval('authorised_user_seq'::regclass) NOT NULL,
"authuser" varchar(255) COLLATE "default",
"password" varchar(255) COLLATE "default",
"user_name" varchar(255) COLLATE "default",
"email" varchar(255) COLLATE "default"
)
WITH (OIDS=FALSE)

;

-- ----------------------------
-- Records of authorised_user
-- ----------------------------
INSERT INTO "public"."authorised_user" VALUES ('58', 'admin', '30fdbe55c1647627f09055dcdeafe621b7d493a71bab465ff24a82c4b3823384be196e9a5f3bf82f', 'admin', '');
INSERT INTO "public"."authorised_user" VALUES ('72', 'test', '985c07fc3578d2149316895b4b9bda5199b74c08764f1e0c26a452f7105907122ea9182c05487081', 'test阿斯打算的', '');
INSERT INTO "public"."authorised_user" VALUES ('279', '阿斯顿个', '7bc340123d3dc64cd44112d8cc5eabfaf31839b3174b85d88ff0b34292b6866e28c4691dbc897b4d', '阿斯顿方', '');

-- ----------------------------
-- Table structure for authorised_user_security_role
-- ----------------------------
DROP TABLE IF EXISTS "public"."authorised_user_security_role";
CREATE TABLE "public"."authorised_user_security_role" (
"authorised_user_id" int8 NOT NULL,
"security_role_id" int8 NOT NULL
)
WITH (OIDS=FALSE)

;

-- ----------------------------
-- Records of authorised_user_security_role
-- ----------------------------
INSERT INTO "public"."authorised_user_security_role" VALUES ('58', '21');
INSERT INTO "public"."authorised_user_security_role" VALUES ('72', '26');
INSERT INTO "public"."authorised_user_security_role" VALUES ('279', '26');

-- ----------------------------
-- Table structure for fund
-- ----------------------------
DROP TABLE IF EXISTS "public"."fund";
CREATE TABLE "public"."fund" (
"id" int8 DEFAULT nextval('fund_seq'::regclass) NOT NULL,
"fund_type_id" int8,
"type" int4 DEFAULT 0,
"amount" float8 DEFAULT 0,
"remark" varchar(255) COLLATE "default",
"info_id" int8,
"user_id" int8,
"create_time" timestamp(6),
"last_update_time" timestamp(6)
)
WITH (OIDS=FALSE)

;

-- ----------------------------
-- Records of fund
-- ----------------------------
INSERT INTO "public"."fund" VALUES ('1', '1', '1', '100000', '', null, '58', '2016-06-28 19:21:59.636', '2016-06-28 19:21:59.636');

-- ----------------------------
-- Table structure for fund_type
-- ----------------------------
DROP TABLE IF EXISTS "public"."fund_type";
CREATE TABLE "public"."fund_type" (
"id" int8 DEFAULT nextval('fund_type_seq'::regclass) NOT NULL,
"name" varchar(255) COLLATE "default"
)
WITH (OIDS=FALSE)

;

-- ----------------------------
-- Records of fund_type
-- ----------------------------
INSERT INTO "public"."fund_type" VALUES ('1', '祭祖基金');
INSERT INTO "public"."fund_type" VALUES ('2', '公王基金');

-- ----------------------------
-- Table structure for info
-- ----------------------------
DROP TABLE IF EXISTS "public"."info";
CREATE TABLE "public"."info" (
"id" int8 DEFAULT nextval('info_seq'::regclass) NOT NULL,
"title" varchar(255) COLLATE "default",
"remark" varchar(255) COLLATE "default",
"info_type_id" int8,
"content" text COLLATE "default",
"picture" text COLLATE "default",
"user_id" int8,
"create_time" timestamp(6),
"last_update_time" timestamp(6),
"type" int4 DEFAULT 1
)
WITH (OIDS=FALSE)

;

-- ----------------------------
-- Records of info
-- ----------------------------
INSERT INTO "public"."info" VALUES ('21', '1234', '234', '2', '<div align="center">
	<blockquote>
		<blockquote>
			<blockquote>
				<blockquote>
					<blockquote>
						<blockquote>
							<blockquote>
								<blockquote>
									<h1 align="left">
										<strong>234</strong> 
									</h1>
								</blockquote>
							</blockquote>
						</blockquote>
					</blockquote>
				</blockquote>
			</blockquote>
		</blockquote>
	</blockquote>
	<p align="left">
		<strong>sdfasdasdasdgsdfdasdfasdfasdfasdfasdfasdfadsfasdf<br />
</strong> 
	</p>
</div>', '/9j/4AAQSkZJRgABAQEAYABgAAD/4RDcRXhpZgAATU0AKgAAAAgABAE7AAIAAAAKAAAISodpAAQAAAABAAAIVJydAAEAAAAIAAAQzOocAAcAAAgMAAAAPgAAAAAc6gAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOmfqeW7tum5jwAABZADAAIAAAAUAAAQopAEAAIAAAAUAAAQtpKRAAIAAAADODkAAJKSAAIAAAADODkAAOocAAcAAAgMAAAIlgAAAAAc6gAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADIwMTY6MDI6MjUgMTA6MzE6NTYAMjAxNjowMjoyNSAxMDozMTo1NgAAAOmX9l5PngAA/+ELHGh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94cGFja2V0IGJlZ2luPSfvu78nIGlkPSdXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQnPz4NCjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iPjxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+PHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9InV1aWQ6ZmFmNWJkZDUtYmEzZC0xMWRhLWFkMzEtZDMzZDc1MTgyZjFiIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iLz48cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0idXVpZDpmYWY1YmRkNS1iYTNkLTExZGEtYWQzMS1kMzNkNzUxODJmMWIiIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyI+PHhtcDpDcmVhdGVEYXRlPjIwMTYtMDItMjVUMTA6MzE6NTYuODk0PC94bXA6Q3JlYXRlRGF0ZT48L3JkZjpEZXNjcmlwdGlvbj48cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0idXVpZDpmYWY1YmRkNS1iYTNkLTExZGEtYWQzMS1kMzNkNzUxODJmMWIiIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyI+PGRjOmNyZWF0b3I+PHJkZjpTZXEgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj48cmRmOmxpPumfqeW7tum5jzwvcmRmOmxpPjwvcmRmOlNlcT4NCgkJCTwvZGM6Y3JlYXRvcj48L3JkZjpEZXNjcmlwdGlvbj48L3JkZjpSREY+PC94OnhtcG1ldGE+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgIDw/eHBhY2tldCBlbmQ9J3cnPz7/2wBDAAcFBQYFBAcGBQYIBwcIChELCgkJChUPEAwRGBUaGRgVGBcbHichGx0lHRcYIi4iJSgpKywrGiAvMy8qMicqKyr/2wBDAQcICAoJChQLCxQqHBgcKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKir/wAARCAECApEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDt/irrOqad4qtotP1K7tY2slYpBOyKTvcZwD14H5VxH/CUeIP+g5qX/gXJ/jXVfGH/AJG+1/68E/8ARklbFx8LtFi8PC/W6vzKYkfBkTbk4/2PevfpVKVKhBzW/kfI4inXrYqoqb28zz3/AISjxB/0HNS/8C5P8aP+Eo8Qf9BzUv8AwLk/xrt/GHw60bw94ffULe6vyyyop3sjgKWwTgKuTj3FZl94K0eHT9NuYNVuIxeW4mPnm2UnPorzIR9Bu+tawr4eaTS622+ZhUwuLpycW9Ur7+djm/8AhKPEH/Qc1L/wLk/xo/4SjxB/0HNS/wDAuT/GtLxN4ZtNN8SSaVpF07vGoZ/tskUKrlQeJCwDdemB+PWpJvAGoReGIdW+0WxMkpVkNzCI1XnDebv2nJ4xWnPQ5VJ21MnSxSlKCu2t7Myf+Eo8Qf8AQc1L/wAC5P8AGj/hKPEH/Qc1L/wLk/xq3pXhSXUI9Tee7gt00+JWLiVHR3b7qbw20Z9c8U6fwns0m3uINX0yW7kYia0N9ApiHY7vMwwP4dablRTtoSoYlrmV/v7FL/hKPEH/AEHNS/8AAuT/ABo/4SjxB/0HNS/8C5P8a1tK8B3d/ZW19cXSxWlwzrm3tprp12kqeI1K9Rx83IqvrXgy80bS31F50ktRP5K74JoZDkEg7ZEXsOxNLnoc3Lpf0H7LFcvPrbfco/8ACUeIP+g5qX/gXJ/jR/wlHiD/AKDmpf8AgXJ/jWVRW3s4djn9tU/mf3mr/wAJR4g/6Dmpf+Bcn+NH/CUeIP8AoOal/wCBcn+NZVFHs4dg9tU/mf3mr/wlHiD/AKDmpf8AgXJ/jR/wlHiD/oOal/4Fyf41lUUezh2D21T+Z/eav/CUeIP+g5qX/gXJ/jR/wlHiD/oOal/4Fyf41lUUezh2D21T+Z/eav8AwlHiD/oOal/4Fyf40f8ACUeIP+g5qX/gXJ/jWVRR7OHYPbVP5n95q/8ACUeIP+g5qX/gXJ/jR/wlHiD/AKDmpf8AgXJ/jWVRR7OHYPbVP5n95q/8JR4g/wCg5qX/AIFyf40f8JR4g/6Dmpf+Bcn+NZVFHs4dg9tU/mf3mr/wlHiD/oOal/4Fyf40f8JR4g/6Dmpf+Bcn+NZVFHs4dg9tU/mf3mr/AMJR4g/6Dmpf+Bcn+NH/AAlHiD/oOal/4Fyf41lUUezh2D21T+Z/eav/AAlHiD/oOal/4Fyf40f8JR4g/wCg5qX/AIFyf41lUUezh2D21T+Z/eav/CUeIP8AoOal/wCBcn+NH/CUeIP+g5qX/gXJ/jWVRR7OHYPbVP5n95q/8JR4g/6Dmpf+Bcn+NH/CUeIP+g5qX/gXJ/jWVRR7OHYPbVP5n95q/wDCUeIP+g5qX/gXJ/jR/wAJR4g/6Dmpf+Bcn+NZVFHs4dg9tU/mf3mr/wAJR4g/6Dmpf+Bcn+NH/CUeIP8AoOal/wCBcn+NZVFHs4dg9tU/mf3mr/wlHiD/AKDmpf8AgXJ/jR/wlHiD/oOal/4Fyf41lUUezh2D21T+Z/eav/CUeIP+g5qX/gXJ/jR/wlHiD/oOal/4Fyf41lUUezh2D21T+Z/eav8AwlHiD/oOal/4Fyf40f8ACUeIP+g5qX/gXJ/jWVRR7OHYPbVP5n95q/8ACUeIP+g5qX/gXJ/jR/wlHiD/AKDmpf8AgXJ/jWVRR7OHYPbVP5n95q/8JR4g/wCg5qX/AIFyf40f8JR4g/6Dmpf+Bcn+NZVFHs4dg9tU/mf3mr/wlHiD/oOal/4Fyf40f8JR4g/6Dmpf+Bcn+NZVFHs4dg9tU/mf3mr/AMJR4g/6Dmpf+Bcn+NH/AAlHiD/oOal/4Fyf41lUUezh2D21T+Z/eav/AAlHiD/oOal/4Fyf40f8JR4g/wCg5qX/AIFyf41lUUezh2D21T+Z/eav/CUeIP8AoOal/wCBcn+NH/CUeIP+g5qX/gXJ/jWVRR7OHYPbVP5n95q/8JR4g/6Dmpf+Bcn+NH/CUeIP+g5qX/gXJ/jWVRR7OHYPbVP5n95q/wDCUeIP+g5qX/gXJ/jR/wAJR4g/6Dmpf+Bcn+NZVFHs4dg9tU/mf3mr/wAJR4g/6Dmpf+Bcn+NH/CUeIP8AoOal/wCBcn+NZVFHs4dg9tU/mf3mr/wlHiD/AKDmpf8AgXJ/jR/wlHiD/oOal/4Fyf41lUUezh2D21T+Z/eav/CUeIP+g5qX/gXJ/jR/wlHiD/oOal/4Fyf41lUUezh2D21T+Z/eav8AwlHiD/oOal/4Fyf40f8ACUeIP+g5qX/gXJ/jWVRR7OHYPbVP5n95q/8ACUeIP+g5qX/gXJ/jR/wlHiD/AKDmpf8AgXJ/jWVRR7OHYPbVP5n95q/8JR4g/wCg5qX/AIFyf40f8JR4g/6Dmpf+Bcn+NZVFHs4dg9tU/mf3mr/wlHiD/oOal/4Fyf40f8JR4g/6Dmpf+Bcn+NZVFHs4dg9tU/mf3mr/AMJR4g/6Dmpf+Bcn+NH/AAlHiD/oOal/4Fyf41lUUezh2D21T+Z/eav/AAlHiD/oOal/4Fyf40f8JR4g/wCg5qX/AIFyf41lUUezh2D21T+Z/eav/CUeIP8AoOal/wCBcn+NH/CUeIP+g5qX/gXJ/jWVRR7OHYPbVP5n95q/8JR4g/6Dmpf+Bcn+Nek/CPVNQ1L+1/7Rvrm78vydnnzM+3O/OMnjoPyryGvU/gt/zGv+2H/tSuTGwisPJpdvzPQyypOWLgm31/JnqdFFFfOH2Z4x8Yf+Rvtf+vBP/Rkld1d6HaL4RWUS3+77PGcHUbgr2/h34/SuF+MP/I32v/Xgn/oySuAr34UXVoQtK1j5CtiY0MVVvG99D27x3otna+GfM8y5cfaIgRd3tzNGQWGcrvJP4c+lTQobnS/Ktbe8t0sLLbEpW+tdzgkD5FPzLgAjBdua8LoprBNQ5XPrf+tRSzKLqOappJq1vnft/Vj0nxbFoV/4ohvNXeTToHG6XzLO5SafaANq7vlIP97Ckd62NQ1uzl8HQTT3Ni2ky3b25gRJQpgCkKifu8hxgEEgDI6149RWn1ROMYuT0Mv7Qkpykor3j0vw+1o/h3WNH0m5We2F3bSR3exkc75UADD5TldvUHnPBFbBt7iXVZ9LGrfvo1fJ+1zHOBn7gvi/5r9a8coolhW22pb/AOS/yCGPUYpOG3n0u3b8T1PR7CdvCWmWt/YxzR20X2grAI7i48uaQ4YQvA/14YcD8Kh8WWNzD4OubW0s4VtY50uyxaOKbYdyBmhWGPb075PPfBx5lRT+rPn5r9b7fPuJY5KHJy9Lb+VuwUUUV2HmhRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAV6n8Fv+Y1/2w/9qV5ZXqfwW/5jX/bD/wBqVx47/d5fL80ellf++Q+f5M9Tooor5o+2Mq3/AORv1D/rwtf/AEZcVq1lW/8AyN+of9eFr/6MuK0Lq7t7G2e4vZ4reCMZeWVwir9SeBV1N/kvyM6Xw/N/myWimo6SxrJGyujAMrKcgg9waZb3Vvdxs9pPHOisULROGAYHBGR3B7VBoS0VFHd281zNbxXETzwY82JXBaPIyNw6jI9aloAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiio3uIY5ooZJY0lmz5aMwDPgZOB3wKAJKKzYvEmhz3gtIdZ0+S5ZtghS6QuW9Nuc59qt3F/aWk0EN1dQQS3DbIUkkCtK3ooPU89qAJ6KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoopGYKpZiAoGSSelAC0VRfXNJj05L+TU7NLOQ7UuWuEEbHngNnB6H8qVNZ0uWyW8j1K0e1dxGs6zqUZicbQ2cZzxigC7RUL3ltHeR2j3ES3MilkhLgO4HUhepAqagAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKpXH+vb8P5Vdqlcf69vw/lQBHVXTf8AkatR/wCvK1/9Dnq1VXTf+Rq1H/rytf8A0OerjtL0/VGc/ij6/ozboooqDQyrf/kb9Q/68LX/ANGXFeQeNLbw7H4mvktr77WVuGub6J/s8TJISchZnQsQOP3arJnnODXr9v8A8jfqH/Xha/8Aoy4qnqfgzTtaW7/tae7u2uAyxtLKCLYMMfu0xsUgfxFS3qTVVPiT8v0RFK3K0+7/ADZ514bSyi1aa7jvLOfWreOaTSbXTltRHcKYzwzRRqxYejqh4OB1xi6HcSR3GkT/ANkRNLLEttHLd2BZZn813klSTIw6DGDz39K9l03wrZaPNC2kzXVnEi7ZLeOQeTNwBlkIIU8Zym0k5zmq+j+CNN0aaKRJrq7NvCYLYXTKy26sSW2gKBls8k5PbpxUv+vx/O5a8zmvhXcTXWoavPcyvNNJa2LPJIxZmPk9STyTXpFY2g+GbTw/Ldy20ss0l1s3tIsagBF2qqrGqqAB7Vs027iSsFFFFIYUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVxviwM/jDQIGt7OXzzP5EzQnz7eRIywZXyRjJHBQjjPJxjsqxde8LWXiK4s5r2W4jez3mEwsAAzAckEHOMdDwecg0nqPueZ6fcMug+HNNSz23yamwTyb/ABdJcDPmPJHJAVAG7OD2K+9ReM5bM+Nrs6j9pjuLDEvnXzWtwJYiMeWkDui7epGNz5PIBr0K2+H2j2Nyt9YzX0OqDJbUvtBkmkJGGLBwyHP+79MVPd+CNK1DVru/vpL2Z7yBIJo1umiR1UY5Ee3Oe4OR7Cm/6+7/AIAv6/E4P4Y3dpb+Lbq2TTY7m8uojMuoWskChIcqNrQxuUj5HIUluRkd69erC07whpul68uq2cl55q2v2RY5rl5kVN2eN5LDp0Bx7Vu029EJbsKKKKQwooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigArmPiFLND4Pma1vRYymRFW482ZNhLY48kFmz0xjHPtXT1m6/oVt4i0o6ffSTRxNIkhaB9rZVgw5wcdKTVxrQ8dNtdWksNjbzR2+3U7NoLMvebbQktz5c6LkM2WJBz2qb7Vcm18LWEFiY7SzvZBcu4MwlvVL84UZfoWwBn5semfRLj4eaPc3zXUs1+5aWGVkmuTMGMRJAJk3MQdxyM/TFadz4Y02f+zRDF9ji0y4+0QQ2qrGm7B4Ix05J4xT/z/wAhd/T/AD/r7zzCysNN03xdoVvP/bDN9ime7eKG+id5iclkUAPtz12gD1r2OBla3jaPftKgr5gYNjHcNzn681QuNCtrnxHaa07yi5tIXhRARsIbrkYzn8a0qfT+u4uoUUUUhhRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABXNeMPEMXhnTJL2WNpnZxFDEv8AHIQSB7Dg10tZl/aW91cxNcxLIbeQSxbhna4UgN9cE0AebWniDxP4Xu4r/wAXRtLpupNltvJs2PQY7cfw/wBc16Dpv/I1aj/15Wv/AKHPUl3aW9/Zy2t5Es0Eq7XRhwRUem/8jVqP/Xla/wDoc9XHaXp+qM5/FH1/Rm3RRRUGhlW//I36h/14Wv8A6MuKukzysxjYIoJAz3qlb/8AI36h/wBeFr/6MuK0ofuH/eb+Zq57/JfkZ0/h+b/NkPl3X/PVfyH+FHl3X/PVfyH+FWaYZo1mWEyIJWBZULDcQOpxUGhD5d1/z1X8h/hR5d1/z1X8h/hU8kiRIXldUUdWY4ApxIVSWOAOST2oAreXdf8APVfyH+FHl3X/AD1X8h/hUpuIFt/PaaMQkA+YWG3B6HPSpKAK3l3X/PVfyH+FHl3X/PVfyH+FPkvbWKYxS3MKSKhco0gBCjq2PT3qYEMoKnIPII70AVvLuv8Anqv5D/Cjy7r/AJ6r+Q/wqzRQBW8u6/56r+Q/wo8u6/56r+Q/wqzRQBW8u6/56r+Q/wAKPLuv+eq/kP8ACrNFAFby7r/nqv5D/Cjy7r/nqv5D/CrNFAFby7r/AJ6r+Q/wo8u6/wCeq/kP8Ks0UAVtt0vPmK2O2P8A61WEbfGrf3gDS0yD/j3j/wB0fyoAfRRRQAUUUUAFQytK0myEgcZJNTUwf8fD/wC6v8zQBD5d1/z1X8h/hR5d1/z1X8h/hVmo/tEPmSR+bHvjUO67hlVOcEjsOD+RoAi8u6/56r+Q/wAKPLuv+eq/kP8ACpopY54UlgkWSORQyOjZVgehBHUUJPFJLJFHKjyRECRFYEoSMjI7cc0AQ+Xdf89V/If4UeXdf89V/If4VJb3MF3D5trNHNHkrvjcMMg4IyPQgiqt1rukWUMM15qtlbxTgmJ5bhFWQDrtJPPUdKAJvLuv+eq/kP8ACjy7r/nqv5D/AAqaGaK5gSa3kSWKRQySIwZWB6EEdRT6AK3l3X/PVfyH+FHl3X/PVfyH+FWaKAK3l3X/AD1X8h/hR5d1/wA9V/If4VZooAreXdf89V/If4UeXdf89V/If4VZooAreXdf89V/If4UeXdf89V/If4VZooAreXdf89V/If4UeXdf89V/If4VZooAreXdf8APVfyH+FSwuzKRIPmU4NSUyP78v8Avf0FAD6KKKACiiigAqOZ2VQIx8zHAqSmSffi/wB7+hoAh8u6/wCeq/kP8KPLuv8Anqv5D/CrNMnnitoWmuZUhiQZZ5GCqv1JoAh8u6/56r+Q/wAKPLuv+eq/kP8ACpnmiiaNZZERpW2xhmALtgnA9TgE/gaq3+taVpTomp6lZ2bOMotxOsZYeoyRmgCTy7r/AJ6r+Q/wo8u6/wCeq/kP8Kq2viXQr25S3s9a064nkOEiiukdm+gBya06AK3l3X/PVfyH+FHl3X/PVfyH+FWaKAK3l3X/AD1X8h/hR5d1/wA9V/If4VZooAreXdf89V/If4UeXdf89V/If4VZooAreXdf89V/If4UeXdf89V/If4VZooAreXdf89V/If4UeXdf89V/If4VZooAreXdf8APVfyH+FHl3X/AD1X8h/hVmigCt5d1/z1X8h/hT4mlWTZNg8ZBFTUw/8AHwn+638xQA+iiigAooooAKwNZu54NQ2xPtUoDjANb9czr/8AyEh/1zH9aAK39pXf/PX/AMdH+FXfD8rza9fPIcsbK2ycf9NLisitTw3/AMhq9/68rb/0bcVcdpen6ozn8UfX9GdLRRRUGhlW/wDyN+of9eFr/wCjLitKH7h/3m/mazbf/kb9Q/68LX/0ZcVpQ/cP+838zVz3+S/Izp/D83+bK+qQrcaZPE4Uqy8homkBGf7qkE/ga4+NZfOlX+yLMyFdyI+j7UAHcZYOeozhWx2yOvaXtol9ZvbynCvjJ2K3Q56MCO3cVkHwbpDMGeIs+DlsKuTxg7QAvGOgAHXIOag0Kc0D2ljaLHBF9kluxLMkVs8W4gjCiNiTyRnsOBxzVCxaW0mlVLSC1d5cTYtgrpv3Hy92SCMBTxjtXTQaFb29uIY5HULKJgyRxIQw6cKgB/EVMumJHYG1t55odxLPKu1nkJ6klgQSfpQNdDmyxuNOsLcRzXc3kIYLZrYeSSEBO4uQHz7HjsM9bmn2sNvqcE13o4s7mXckJjjiEcR2kkfKxLHAPJx7AZNa0mj20kVpGWmVbRdsflylCRjHJXB/KhdGtluYZw9yzREkCS5eRTkEchifWm92SlpY5m2DO1zbyCH+zZ7tF2WcPltM21MADf8AKpHzZGeAema1NBcS3odp7lXNvkQSSu6PluXG5m6YA7Y/GtT+y4VaV4SYpHYMsiqpMXyhflyCBwoqS1sILSCCNF3mBSqSOAWGevOO/tQtv67AWaKKKQwooooAKKKKACiiigAooooAKZB/x7x/7o/lT6ZB/wAe8f8Auj+VAD6KKKACiiigApg/4+H/AN1f5mn0wf8AHw/+6v8AM0APrkNe0U6j4imiMsE0s9mxjhDNbyCMMgeNpVVgY264IzngcE46+qcWmxRavcalvkeeeNIsMQVRVycKMcZLEmlbUDhdP8OW+jeI7Ma5Z6dFGySSo6i1ZQU29SLSIjlgQQ3UVkfaJdI1DUra/W+064MZvJA2q5aVD5gKjMzZ+RUAfYzDB+78pHpOteH7TXfs32t5k+zyiQeUwG8cZRsg5U4Ge/HUVW/4Q7SI01FLOAWSajAsEqWqJGoC7sMAFxu+bqc9BTDoZDxWUOk38/h8XMWmtGsSQwB4kuJuFjaF0YMBnaCw+Vhgg9SaPgiKWJ9EinikWRdNuHZmummDhmhAZdxyg4I24ABBxnrXW2Wh/ZdTN/daleX9x5JhQ3IiARSQTgRovUgdc9KNI8PWmjMzQSTTM0SQhpmBKIo4UYAwMkk+pP0pPZ/13/z/AKsBD4QnifwnpcKSo0sdlCXQMCyZQYyO2cGtusnQvD0GgRSJb3NxcbwihrgqSqIu1VG1QMAevPqa1qqTu7gFFFFIAooooAKKKKACg8g0UUPUDyKP4g+IPh0svhzxvp93rmofd0G+s4yf7XyQFjfrskGRuJzwCeTgv3vgu08RW+gtL4yu4p9Vu5muJIoBiO1DABYU5OQoHXuSevU7zRo7IzorFDuQkZ2nBGR6cEj8adTv33/r+mD1f9f18v8AgWKZH9+X/e/oKfTI/vy/739BSAfRRRQAUUUUAFMk+/F/vf0NPpkn34v97+hoAfXKeP7eeXSIpYbS7uYrcvNN9nujCAFUsu4CRNw3BemSADjmurrP1jQ9O12za31S0hnGxlR3iVmi3DBKlgcH39qTu1oNWvqebzt9vvLTUUv76202C1aVZB9tvQjkkMGlguGAIAY53AhWAIOOO5sJ9cXTbX7DbWF/AYVZLie8ngeQEZBKPHIw4/vOT9OlTan4V07VBE03nRzwqipPFJhsKwZQwOVcAjOGUgHJAzWjeW8tzbGKC8ns3yD50CoW+nzqw/SqJRyegx61fSJrlzpmnXV1IzrHNNqLg26bipWNBAQo465y3c9h2lVdM0+LStNhsoHkkSIYDykFmJOSTgAZJJ6CrVLyH5hRRRQAUUUUAFFFFABRRRQAUUUUAec+JfEeu/D7xdPrWsb9R8E35QTPEhaXR5AqpuKjJaJsZOOhJ4z9+94G1PxL4r1S48T6nG2l6BND5Wk6XIuJpELA/aZfQsBwvOAfxbtpI0ljaOVFdHBVlYZDA9QRTqFp/X9f156g9f6/r5/8Pcph/wCPhP8Adb+Yp9MP/Hwn+638xQA+iiigAooooAK5nX/+QkP+uY/rXTVzOv8A/ISH/XMf1oAzK1PDf/Iavf8Arytv/RtxWXWp4b/5DV7/ANeVt/6NuKuO0vT9UZz+KPr+jOloooqDQyrf/kb9Q/68LX/0ZcVoJIse5ZGCncTycZyc1n2//I36h/14Wv8A6MuK1aue/wAl+RnT+H5v82M8+L/nqn/fQo8+L/nqn/fQp9FQaDPPi/56p/30KPPi/wCeqf8AfQp9FADPPi/56p/30KPPi/56p/30KfRQAzz4v+eqf99Cjz4v+eqf99Cn0UAM8+L/AJ6p/wB9Cjz4v+eqf99Cn0UAM8+L/nqn/fQo8+L/AJ6p/wB9Cn0UAM8+L/nqn/fQo8+L/nqn/fQp9FADPPi/56p/30KPPi/56p/30KfRQAzz4v8Anqn/AH0KPPi/56p/30KfRQBGZ4scOpPoDkmnRKVhRT1CgGnUUAFFFFABRRRQAVGWEcxLnAZQAT04z/jUlFADPPi/56p/30KPPi/56p/30KfRQAzz4v8Anqn/AH0KPPi/56p/30KfRQAzz4v+eqf99Cjz4v8Anqn/AH0KfRQAzz4v+eqf99Cjz4v+eqf99Cn0UAM8+L/nqn/fQo8+L/nqn/fQp9FADPPi/wCeqf8AfQo8+L/nqn/fQp9FADPPi/56p/30KPPi/wCeqf8AfQp9FADPPi/56p/30KPPi/56p/30KfRQAzz4v+eqf99Cjz4v+eqf99Cn0UAM8+L/AJ6p/wB9Cki53sOjNkfkB/SpKKACiiigAooooAKjl42N2Vsn8iP61JRQAzz4v+eqf99Cjz4v+eqf99Cn0UAM8+L/AJ6p/wB9Cjz4v+eqf99Cn0UAM8+L/nqn/fQo8+L/AJ6p/wB9Cn0UAM8+L/nqn/fQo8+L/nqn/fQp9FADPPi/56p/30KPPi/56p/30KfRQAzz4v8Anqn/AH0KPPi/56p/30KfRQAzz4v+eqf99Cjz4v8Anqn/AH0KfRQAzz4v+eqf99Cjz4v+eqf99Cn0UAM8+L/nqn/fQo8+L/nqn/fQp9FADPPi/wCeqf8AfQpAwkmBQ5CqQSOnOP8ACpKKACiiigAooooAK5nX/wDkJD/rmP6101czr/8AyEh/1zH9aAMytTw3/wAhq9/68rb/ANG3FZdanhv/AJDV7/15W3/o24q47S9P1RnP4o+v6M6WiiioNDKt/wDkb9Q/68LX/wBGXFatZVv/AMjfqH/Xha/+jLitWrnv8l+RnT+H5v8ANhRRRUGgUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFczr/8AyEh/1zH9a6auZ1//AJCQ/wCuY/rQBmVqeG/+Q1e/9eVt/wCjbisutTw3/wAhq9/68rb/ANG3FXHaXp+qM5/FH1/RnS0UUVBoZVv/AMjfqH/Xha/+jLiuK1fxPf6f8QpUh12xuEisH22UaMQ8nmDEOzzeZj0B6/7Ndrb/API36h/14Wv/AKMuK5afwRrr/wBom31HT4lk1f8AtS2jeB3LMMFQ7hhtHHICn61U/jXp+iX/AAfkZ0/gfq/zZjaB4m8QLYPCmpQ3Tyafc6lcPNCzy2zBiojBMhXAYcDbgAdDmspfFHivU1trE6xc7rpyZBDFiURiONiB5MDMpO/KsAcDrXWaZ4D1fSE1IxXtldya1byLfF4vJ8uUhsNGVByuWwQQOmfakvPhdBP4Y+zQzBdRNosbNKEmjaUIF3b5I2kQcAYQrgAYAqNv69f+B6mu7/ry/wCCXPh5qWtXr6tb63cyXIs5ljiaVSjKpXIBDRRsTgjLN19B1Pa1h+F/DSeG7HyY5y5dE8xFghjUOBgkeXGpP1bJrcq5EoKKKKkYUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVxfj298R6UF1DSb6KDT0iKSRmaKJvNJOG3Sxsu0DtkEngc9e0rlfFXhF/EuqWcymO2Nup23omm86E5/5ZorKoPfeSe3ymk7jRwmh6v4puPsuk6Xrk0t3exvPFf3c+LdyDyFWa1DtwOiMQOvHNWNX8aX58Wagtlql1bmC7gshBC0ZDIquZ2VZRt3ZXAPHYe1adp8Mr+1t7kS6k18kl28v2K5vJxFKu5SrlkKlZeDlirjOOOKtax8PrnVtY1B2i0yO11EwCSZlMk8CKvziPK43M38WffGafa39f1sLuv6/rqZKeMtR1PXtMFvdXKW0fnFDJhJJlNoJFMqr8hIJyMDFV9M8e6tFNYyXuszGGbTlmne80sNHHI0qpuGwRkoAfvbiOvU8V0k/gKUeJku7AQQWUSybQ05ZmJtxCoCeWAoGP7zE/pVbSvAerWfkjVDpmowR6O2n/Zw0kIYlw2C2GJGM/MADnHHejS/9dn/wBP8Ar7/8jMTxHr1gmvs+ox3QfWI7JW2OPKEgwWizIdoA5A55556VNpPiPR7j7DpmoXmt3l75/wBgFyuo+QXYMQGaKO43Y/2yvPFXR4A1I6VcxBrKCW41eK9EKSu0cUSYAQMVBJwPQCtYeCLTTYYn0yCS/njvDdIl9qcsUcbkk7gqKVyCf7nQnJpP4f67L/gj/r8/+AP+Gt3c33gGxnvbia5mZpQ0s0hdjiRgMk8ngV1VYng/QpfDfhW00y4lSWaLcXaPO3LMWIGewziturluIKKKKkYUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFc5491r+wfBd/dLMYZnTyYXU4YO3AI9wMn8K6OszxDZ3WoaPLa2MFlNLL8n+m58tFIILYAJJwTxx160pbDjueeXviXXIvIso7r7cNO1aztUmtC0T3mYmZkctIwOTgHJwTyav6z4kg1iTwzdxnWLL7TdGG6t4GuUwArbkPl4DEMO3OB6Zp9h4A1TR7G0sIZbLUre1vVv0leR7SUzDIw/yyhlxj+6eK2da0nxFrVxpcyR6ZYyWE7XG77RJOC2xlC48tODnrnj0NP8AzX6X/Ulfp/n/AMA8ml8R6kLaQ/23OJBZSP8A8huYN5gnwDs6b9vAToV+bNexeNdRk0zwFqN1DK8c/wBn2ROjEMHbCjBHOcmsA+DtaPiVNUMEWxbUwGL/AISK83klt27zPL3Af7PTvW9JoN/rOswXXiGS3WysnElrYW7M6tIBxJI7AbiDnCgY6Hmi148o72lzf10LnhS9Go+EdKuvNeZpLVN7u25iwGGye5yDmteuesNDv9D1qVtJmhk0i7laWa0nJVrZzyWiIBBBPJQ4weh5roabd3cSVtAooopDCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK5nX/APkJD/rmP6101czr/wDyEh/1zH9aAMytTw3/AMhq9/68rb/0bcVl1qeG/wDkNXv/AF5W3/o24q47S9P1RnP4o+v6M6WiiioNDKt/+Rv1D/rwtf8A0ZcVee5IcrHEXwcEiqNv/wAjfqH/AF4Wv/oy4rSh+4f99v5mrnv8l+RnT+H5v82Q/aZf+fdvzP8AhR9pl/592/M/4VZoqDQrfaZf+fdvzP8AhR9pl/592/M/4VZooArfaZf+fdvzP+FH2mX/AJ92/M/4VZooArfaZf8An3b8z/hR9pl/592/M/4VZooArfaZf+fdvzP+FH2mX/n3b8z/AIVZooArfaZf+fdvzP8AhR9pl/592/M/4VZooArfaZf+fdvzP+FH2mX/AJ92/M/4VZooArfaZf8An3b8z/hR9pl/592/M/4VZooArfaZf+fdvzP+FH2mX/n3b8z/AIVZooArfaXHLwMB3Of/AK1WAQygjoRkUvWmQf8AHvH/ALo/lQA+iiigAooooAKilm8tgqqXYjOBUtMH/Hw/+4v8zQBD9pl/592/M/4UfaZf+fdvzP8AhVmigCt9pl/592/M/wCFH2mX/n3b8z/hVmigCt9pl/592/M/4UfaZf8An3b8z/hVmigCt9pl/wCfdvzP+FH2mX/n3b8z/hVmigCt9pl/592/M/4UfaZf+fdvzP8AhVmigCt9pl/592/M/wCFH2mX/n3b8z/hVmigCt9pl/592/M/4UfaZf8An3b8z/hVmigCt9pl/wCfdvzP+FH2mX/n3b8z/hVmigCt9pl/592/M/4UfaZf+fdvzP8AhVmigCt9pl/592/M/wCFTRSCVMgY5wQe1Ppkf35f9/8AoKAH0UUUAFFFFABTJZBEm4jPOAPWn0yT78X+/wD0NAEP2mX/AJ92/M/4UfaZf+fdvzP+FWaKAK32mX/n3b8z/hR9pl/592/M/wCFWaKAK32mX/n3b8z/AIUfaZf+fdvzP+FWaKAK32mX/n3b8z/hR9pl/wCfdvzP+FWaKAK32mX/AJ92/M/4UfaZf+fdvzP+FWaKAK32mX/n3b8z/hR9pl/592/M/wCFWaKAK32mX/n3b8z/AIUfaZf+fdvzP+FWaKAK32mX/n3b8z/hR9pl/wCfdvzP+FWaKAK32mX/AJ92/M/4UfaZf+fdvzP+FWaKAK32mX/n3b8z/hUkU3mMVZCjAZwalph/4+E/3G/mKAH0UUUAFFFFABXM6/8A8hIf9cx/Wumrmdf/AOQkP+uY/rQBmVqeG/8AkNXv/Xlbf+jbisutTw3/AMhq9/68rb/0bcVcdpen6ozn8UfX9GdLRRRUGhlW/wDyN+of9eFr/wCjLitKH7h/3m/mazbf/kb9Q/68LX/0ZcVpQ/cP+838zVz3+S/Izp/D83+bHHO04IBxwTXmtl4zvAmq3MWt6ffTKpnW1jt9x2Dco2K1yMYCb2XGfm6kmvSyMggHHuO1cufB8s+pX899qlzdC4tkhjeYrxjfuDRKqxOMMMb1bnNZmqsVdBvdfttNCeKLS9+ztCd8kNtukDsexinkkPUgYRccfdxWdq1xp26Gy0tvEcVxchv38zaofKUYywTq55GBwPU9Ad/wv4WXQr29uZ7fTxcTFUSaygECmMAfL5YGF+bJzlifUAAC59j1K48TwXlzFaw2lrHKkZjnZ5Jd5XBKlAF4U92603ZsS0Ob1fU7nT/DFlbaFdarJKlzFGZL/T7gzTEyp1kcxhQc4+YgMDtBFQf8JLrEfiG9ke7t0WAQQtazW5wx8zEm0pOyhwHUnqcFQQMZPXatpJ1TUNPd47Uw2ztI7yQrJIDjChNykLzySMH5QO5rPtdA1SPS4tNe4sY7Q2kkE0cVsmzfuysgTZtORncp454oT6hbSxk6xqup300txouq6na2ksWbYxacbiOU9MjZA7IvB+824noAMExadc6vHrFrZwa7q11DuO22urIQSvCpUbvMltwHIz8wyDg5DZ4OveeCbTV/sk+oeXbTwWqweRb28EsCYyfkEsTYHPbHAFVfDfhG+0jXUu3isLeFUZXECwM8megylrEVHf7x6DinHRg9jEuvGF5capAz+JNHsdv2yNoCpHl7G2r5g84ZYgZU4GOeDW54G8QXOppb2c+p2OpBNOimZ7cHzI3PBWQmRstxycD6UW3hLW42ib+1rCLyHuvKT7E8mFmcsct5q5OMdAMe/WtDw/oGoaRfRte3ttdQQWEdpEYoGibCk/eBZgeO4I+lKOm/9b/8AJeX9ao6KiiigAooooAKx/Fmpapo/hi71HQdMOq3tsFkWyU4aZAw3hf9rZuI6844PQ7FFJ36DW5wN38YPDg8FWmu6Q0mp3Oov9nsNKh/4+ZrjjMRXnaVJG49ACCM5XPa6dJdy6XayalEsF48KNcRIcqkhUblByeAcjqax7PwJ4bsPGV14ptNKhj1i6TZJcAf99MB0DN0JHJx7nPQ1Wlv6/r+vvnr/X9f19xTIP8Aj3j/AN0fyp9Mg/494/8AdH8qQx9FFFABRRRQAUwf8fD/AO6v8zT6YP8Aj4f/AHV/maAH1yN9qFzFOIL251KEFizN5trAAM5AUk/N2yN3Tk9cV11crL4Zv5ZTNHNb2swcOHRI2ZjnJO8RKV7+ufajqHQsW+p3UUEl8x1Ca2EZCLcRwYd8gLtMZyQfXBBznNUYdXnhmhU313NGsEbSKvlHErjdtJYbtuAemce2K09P0e9s5p/MeFllRg8iCNPMPOCVWIHv/fP40600LaYmu4rdjbweVEkYxklQHZmxnJ6ew55PQD+vyM5dVuZL7/j5uoIppmJEMfnMo8lGAAKtxknoKG1nUbjw2WXyTKsUTPKJ2ST5iOdoTHPI4Pr9KvW+gT+cJ2uPsbLKzKtuRJhTGqAbnX/Z9KdNo1wNJg0+3W3kCRrG1zIxVwAwJwoU56dMin/wBEd/f3EUs7zxsHhWJPJgnfa3mEg8hc8YBBVQ1VIpy7Eql3byw3EA+a8uGDB3wQVkC+npWzPpIu7u5a4dhFL5JXynKsChJ69uo6c/SoZtIkWdVtI1ETSxSSzTXUkkh2NnADA/+hd6S3KexsUUUUCCiiigAooooAKKKKACiiigApkf35f97+gp9Mj+/L/vf0FAD6KKKACiiigApkn34v8Ae/oafTJPvxf739DQA+sDVdRnTVnW0uFhFlbPK4kjZklbj5eCMkAj1+8OK36y9S0ubU7mMtLHDHbkPFhSxdv9rp8vH3R19RQBWt9Unt9VuEv45BEwiDSKcpC5QcY6gE9+nTNZN1OBLOltcalH/pscalzcthCgJGMgk5ycA5x7VvwRanDdTTfZbRmnK72+1MBwMZA8vj6ZP1qGTSr0SSyed9oad98iJO9qgIUKCCoZjwOhbHtR1uBmeF57iS/i866uJg8EpIlEwGRIAD87EHj0xjoa1b2/aPxLY26s4iCt52CdoLcJn6kHFQaXpmpabbhEihaQBsM2oTMvJJ+4Vx3/AM5q/FpEX2OeG6dp5Lk7ppiNpY9segGOB2o7AaFFVrJLyONo72SOUqcJKgwXHqw6A/Tg+3SrNABRRRQAUUUUAFFFFABRRRQAUUUUAFMP/Hwn+638xT6Yf+PhP91v5igB9FFFABRRRQAVzmuQyyajmON2GwDKqTXR1SuP9e34fyoA5j7Lcf8APCT/AL4NaHh1WTXL1XUqwsrbIIx/y0uK06q6b/yNWo/9eVr/AOhz1cdpen6ozn8UfX9GbdFFFQaGVb/8jfqH/Xha/wDoy4rSh+4f99v5ms23/wCRv1D/AK8LX/0ZcVpGJWYnkE9cMRn8que/yX5GdP4fm/zY+imeSvq//fbf40eSvq//AH23+NQaD6KZ5K+r/wDfbf40eSvq/wD323+NAD6KZ5K+r/8Afbf40eSvq/8A323+NAD6KZ5K+r/99t/jR5K+r/8Afbf40APopnkr6v8A99t/jR5K+r/99t/jQA+imeSvq/8A323+NHkr6v8A99t/jQA+imeSvq//AH23+NHkr6v/AN9t/jQA+imeSvq//fbf40eSvq//AH23+NAD6KZ5K+r/APfbf40eSvq//fbf40APzjrTIf8Aj3j/AN0fyo8lD13Eehcmn0AFFFFABRRRQAUwf8fDf7g/mafTWRXxuHI6EHBoAdRTPJX1f/vtv8aPJX1f/vtv8aAH0UzyV9X/AO+2/wAaPJX1f/vtv8aAH0UzyV9X/wC+2/xo8lfV/wDvtv8AGgB9FM8lfV/++2/xo8lfV/8Avtv8aAH0UzyV9X/77b/GjyV9X/77b/GgB9FM8lfV/wDvtv8AGjyV9X/77b/GgB9FM8lfV/8Avtv8aPJX1f8A77b/ABoAfRTPJX1f/vtv8aPJX1f/AL7b/GgB9FM8lfV/++2/xo8lfV/++2/xoAfTI/vy/wC//QUeSvq//fZ/xpyqFXCjAoAWiiigAooooAKZJ9+L/f8A6Gn0jKGXDDIoAWimeSvq/wD32f8AGjyV9X/77b/GgB9FM8lfV/8Avtv8aPJX1f8A77b/ABoAfRTPJX1f/vtv8aPJX1f/AL7b/GgB9FM8lfV/++2/xo8lfV/++2/xoAfRTPJX1f8A77b/ABo8lfV/++2/xoAfRTPJX1f/AL7b/GjyV9X/AO+2/wAaAH0UzyV9X/77b/GjyV9X/wC+2/xoAfRTPJX1f/vtv8aPJX1f/vtv8aAH0UzyV9X/AO+2/wAaPJX1f/vtv8aAH0w/8fC/7h/mKPJX1f8A77b/ABpVRUztHJ6knJoAdRRRQAUUUUAFUrj/AF7fh/KrtUrj/Xt+H8qAI6q6b/yNWo/9eVr/AOhz1aqrpv8AyNWo/wDXla/+hz1cdpen6ozn8UfX9GbdFFFQaGVb/wDI36h/14Wv/oy4rVrKt/8Akb9Q/wCvC1/9GXFatXPf5L8jOn8Pzf5sKKKKg0CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAqlcf69vw/lV2qVx/r2/D+VAEdVdN/wCRq1H/AK8rX/0OerVVdN/5GrUf+vK1/wDQ56uO0vT9UZz+KPr+jNuiiioNDKt/+Rv1D/rwtf8A0ZcVzviP4gyWGl6zJo2l3E02lTLBLPOI/IViwHQSBzweMDrXRW//ACN+of8AXha/+jLivPvFngLUzp/iW+ht9PvJLy5E8CJZtLdBdy5CvkbeM5ADZ59aqp8S9F+hFHb5v82d1pfiePUNck0ibT7yyvIrYXLLP5ZUoTgYKO3esrwvrPiPxPpk18l3pdoqXMkAjNhJIcKcZz5w/lWFo8Euh+LP7R03SpLhLiyeK4jtdFmsI4AnzggOD5jsRtwPaup8AaTcaR4NtYr+MxXUzPcTIRgqzsTg+4GBS8/63/yGr2/rt/mbFhFqkbP/AGpeWlwCBsFvaNDj1zukfP6VdoopFBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVzHibxPe6JrujWFnpz3S38pVyCmWABO1MuuGHBy3GD1zXT159470CS88WaLqkttdX9nCWSS3t4mcxgK7Mw28gk7ADnOQMUdVfa4+jCw8ba3cavp6TLYfZbzVLixMawOJEWPo27zCCT/u07VvihbaXrmq24W2mgsIzGkfmMJp7gcsBgHagGQWI6jgmsG80bXNJ8N6BeW1hctfJdXV48cMDStA8iEoGUAnrgHI69af4h0TVLga1qcv9rahc3Np9lVItNRUiI/5Z85kYZwd0ahSepIzhapen+S/W4aX9f8/8jqNH8ff2p4g07TPI05/t0Ly+ZZal9oMO1d2118tcH8fWuyrzLS4br/hNfDE7HWrqG3tJIZnu9NeJbdigAUERJxnuc9Otem1bt/XqSr/16BRRRUjCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACsrxLqsmj6HNc281hFc/dh/tCcQxu3XbuPfAOBkfUVq1zvj21uL3wJqltZwSTzyxBUjiUszHcOgFJ7DjvqZUviTxNfXurJo9naommWqOyS28kpmnK7jGjB0yMYwQDnI9RT9c8aalp/hKK9sNGuZr82/mz+fayQw220DeW34J5zhQcnr9eR1XRNY1S8v7jTPCPmy3NssFy1/DCPs8i4XfCX2ljtzkjI3dGIAzf8QaAZNK8Kx+HLLVJFsp/KIMM0TJhclyhePaSx+9uX/ep9P68/wAP06iXn/Wi/Hc1dE+It5rWrWem2Gn2GoTSRiS5mtbyRFhTIBcrJEp/iyFBJ/nVbxL4+1bSNa1O1sfs0kNkkbDzNLuCQzvt2swcDGOQ2MN0Fc3e+FvE0t1ZT6rYalNImqL5U/mvK8MBYdGW5coOP7pI/v10vi6zV7HWrXSoZi90i+Yn9i3sss0kYGzFwGC9VGDgj1zk0N6J/wBf1+oJa29C7pHjTUr7xFbadPHbmKS9uLZnFvJE5WOFHB2sxKkljkHp060sHiTxDLc3qXifYBDdSRwL/wAI9eXPmRg/K+9HA5qp4etvtl5p0/iL7VeXP2YQtFc6RfAIWQKwLSO0XI4ZtoB5PepL7wF4c0m5lmIvVW7laQRW+kQ3ax/7I/0dyi88DI/nQ9GJar+v6/4Y6Dwlquq6raXr61a+Q0N28UDfZJLfzogBh9khJGcmt+uO+Hmlva6dd3d3p0drNJdSJA7WEVtM1uCNu5URepBPI/pXY02CCiiikMKKKKACiiigAooooAKKKKACiiigAooooAKKKKACqVx/r2/D+VXapXH+vb8P5UAR1V03/katR/68rX/0OerVVdN/5GrUf+vK1/8AQ56uO0vT9UZz+KPr+jNuiiioNDKt/wDkb9Q/68LX/wBGXFaLzxxthmwfYZrOt/8Akb9Q/wCvC1/9GXFX4okYMzKGJduoz3NXPf5L8jOn8Pzf5sPtcP8AfP8A3yaPtcP98/8AfJp/lR/881/75o8qP/nmv/fNQaDPtcP98/8AfJo+1w/3z/3yaf5Uf/PNf++aPKj/AOea/wDfNADPtcP98/8AfJo+1w/3z/3yaf5Uf/PNf++aPKj/AOea/wDfNADPtcP98/8AfJo+1w/3z/3yaf5Uf/PNf++aPKj/AOea/wDfNADPtcP98/8AfJo+1w/3z/3yaf5Uf/PNf++aPKj/AOea/wDfNADPtcP98/8AfJo+1w/3z/3yaf5Uf/PNf++aPKj/AOea/wDfNADPtcP98/8AfJo+1w/3z/3yaf5Uf/PNf++aPKj/AOea/wDfNADPtcP98/8AfJo+1w/3z/3yaf5Uf/PNf++aPKj/AOea/wDfNADPtcP98/8AfJo+1w/3z/3yaf5Uf/PNf++aPKj/AOea/wDfNADRdQk4D/mDUtMMMZGNij6CiH/j3j/3R/KgB9FFFABRRRQAU15UjHznFOqIor3J3DOFGAfqaAE+1w/3z/3yaPtcP98/98mn+VH/AM81/wC+aPKj/wCea/8AfNADPtcP98/98mj7XD/fP/fJp/lR/wDPNf8Avmjyo/8Anmv/AHzQAz7XD/fP/fJo+1w/3z/3yaf5Uf8AzzX/AL5o8qP/AJ5r/wB80AM+1w/3z/3yaPtcP98/98mn+VH/AM81/wC+aPKj/wCea/8AfNADPtcP98/98mj7XD/fP/fJp/lR/wDPNf8Avmjyo/8Anmv/AHzQAz7XD/fP/fJo+1w/3z/3yaf5Uf8AzzX/AL5o8qP/AJ5r/wB80AM+1w/3z/3yaPtcP98/98mn+VH/AM81/wC+aPKj/wCea/8AfNADPtcP98/98mj7XD/fP/fJp/lR/wDPNf8Avmjyo/8Anmv/AHzQAz7XD/fP/fJo+1w/3z/3yaf5Uf8AzzX/AL5o8qP/AJ5r/wB80AM+1w/3z/3yalVgy5U5FN8qP/nmv/fNJCoQyKvQPx+QoAkooooAKKKKACkZgq5Y4FLUcyhzGrdC/P5GgBv2uH++f++TR9rh/vn/AL5NP8qP/nmv/fNHlR/881/75oAZ9rh/vn/vk0fa4f75/wC+TT/Kj/55r/3zR5Uf/PNf++aAGfa4f75/75NH2uH++f8Avk0/yo/+ea/980eVH/zzX/vmgBn2uH++f++TR9rh/vn/AL5NP8qP/nmv/fNHlR/881/75oAZ9rh/vn/vk0fa4f75/wC+TT/Kj/55r/3zR5Uf/PNf++aAGfa4f75/75NH2uH++f8Avk0/yo/+ea/980eVH/zzX/vmgBn2uH++f++TR9rh/vn/AL5NP8qP/nmv/fNHlR/881/75oAZ9rh/vn/vk0fa4f75/wC+TT/Kj/55r/3zR5Uf/PNf++aAGfa4f75/75NH2uH++f8Avk0/yo/+ea/980eVH/zzX/vmgBn2uH++f++TUiSpIPkOaTyo/wDnmv8A3zTQipcrtGMocgfUUAS0UUUAFFFFABVK4/17fh/KrtUrj/Xt+H8qAI6q6b/yNWo/9eVr/wChz1aqrpv/ACNWo/8AXla/+hz1cdpen6ozn8UfX9GbdFFFQaGVb/8AI36h/wBeFr/6MuK0ofuH/eb+ZrNudO1D+2Jb7Tr22h86COF0ntWl+4zkEESLj/WH16Ui2uvqMDU9N6k/8g6Tuc/8961klLW/5mEXKKtyvd9u/qa1ctP4wj+z6xe28lvHZafAPKluAV8+YruXaSRlDwBj7xPBxgnU+z+IP+gnpv8A4LpP/j9Zt34Yv7yaaeS70oXE3Dzf2YzNtwFZQWmO0Mo2nGOPfmocV0kvx/yNFN31i/w/zJJfFbxaXJeHT2UC382FbieO2acjG47ZCCiAkZZsH2PGcZPiK32HzXtoHaKaJZZY7qBoyjHByVmZYzk8b2wcE+oFqTwPdSW00X9pw5lh8nzHjuZXRMgkIXuW28qOmOgqSDwfqtrfG6ttfCOxi3B4p5dwQsQpL3DHad5yM44Hvl8qvv8AmTzyt8L/AA/zGxeNXkMZjNldsbhkaKzkMnmoFUkQv0lZdwJGFJwwA+XmjbfEK/NvJJcafatsDSsVF4BHHkgFits68YILBipIOK1JPDGtz6ebW71+G4LTCZ5pLJ95I6bSJQI+n8AUjqCCSayv+FZTfYfsra2zILc26ki5+RT97A+0bfmwCRjbwOKOVd1+P+Q+d/yv8P8AM6VdS1C71RrG1FrDJDapJcGQM6xu4baUIKlwCpBBCHkHPaq91d69pl7pwvLzTrmG7u1t3WKxkiYAqxyGMzD+H0pth4e1fTryW5g1a0ZpYY4SJbOWT5U3Y5acsT8xyST2qW+0bWtQktGm1WwU2s4nTZp7jLAEYP77p8xp8sbqz6+ff0EpytrF/h29e5Tn8Y3UlrZ3OnaDfyQXFysQkkaABwWIO0edkHjjIA9a1rTWzeJfo1hc2VxZoGaO5MZzlSQQUdhjj1rm1+HEYtYIX/sSRopRKZpNGzJKck4dvN5Bz0rQsvCt9pv20abd6VaJeqA8cGlFEXAIyoEuM8981PL7r95X+f8AkUpvmXuu3y/zJNGn8S6todlqP9o6VD9qgSby/wCzZG2blBxnzxnrW3YR38cTDU7m2uJN3ytb27QgD0ILvk++azbDS9b07Trayg1TTzFbxLEhbT3JIUYGf33Xip/s/iD/AKCem/8Aguk/+P1TjG7s1+P+RCnOyvF/h/matFZX2fxB/wBBPTf/AAXSf/H6Ps/iD/oJ6b/4LpP/AI/S5V3/AD/yK55fyv8AD/M1ay/EfiLT/CmgzaxrMjRWVu0ayyKu7YHdU3EegLAnHOM9aT7P4g/6Cem/+C6T/wCP1HcafrN3ay213e6TPBMhjkik0x2V1IwVIM2CCO1JxXRr8f8AIFN31i/w/wAyxqHiDSdL8PSa7f6hBFpccInN1vyhQ9CCPvZyMAZzkAZzVjTr6LVNLtb+2DCG6hSaMOMMFZQwz74NeZ2fwRW0lson197vSNPunu7TRLq2aSzhkb/Z8zcwHUBmIGT/AHjn0D7P4g/6Cem/+C6T/wCP1XLH+b8/8hc8v5X+H+f9fLXVpkH/AB7x/wC6P5Vm/Z/EH/QT03/wXSf/AB+kW119EVRqem4UYH/Euk/+P0uVd/z/AMh88v5X+H+ZrUVlfZ/EH/QT03/wXSf/AB+j7P4g/wCgnpv/AILpP/j9HKu/5/5Bzy/lf4f5mrRWV9n8Qf8AQT03/wAF0n/x+j7P4g/6Cem/+C6T/wCP0cq7/n/kHPL+V/h/matMH/Hw/wDur/M1m/Z/EH/QT03/AMF0n/x+k+y6+HLf2npuSAP+QdJ/8f8AejlXf8/8g55fyv8AD/M1qxfEt9qemabcahYyWSwWkJleO4jZmmI52ghgE6YBw2SenHMv2fxB/wBBPTf/AAXSf/H6o6l4d1DVgpvbrSWmRSIrgaY4lhJ7o/nZU98ik4rpL8/8gU31i/w/zDWvFsekyWCPb3AacGSYfY5pAkYjZjhlXGQQoPoCSRVSTxldx6foci6VczTai6RyARCIbipLKqyurZ4yCQVx3qvqXgPUNWKte6+XcWxtyyxzruBABYqJ9uSF5wMHJyDxh994FvNRay+2arbTRWWfKiltZZBknJJZ5yxPTnPGBjFVyxvut/P/ACFzyt8L28v8y1b63rEl9BJI9kLObUpLLyPszCVQu/B3+YQT8n93vTNU8cQ6ffajHbrFefYYmJt4nHmBlUs7Oc/JGPlXOCSx46U+LwxqsMcCLq9mRBePeKWsXJLtuyCfO5Hzn34HNVr7wbrd/dahLP4njEd/CYZYRpw2qm3ACkuWAGScZxkknNLlVt/z7L/gj53f4X+Hd+faxY0rxl/aOuWun/8AEom+0o7btP1T7S0e0Z+ZfLXGfrXVVyVv4W8RRanbXt14qS9e1VxEk+mIqruGD9x1J4962Ps/iD/oJ6b/AOC6T/4/T5Y91+P+QlOXWL/D/M1aKyvs/iD/AKCem/8Aguk/+P0fZ/EH/QT03/wXSf8Ax+lyrv8An/kPnl/K/wAP8zVorK+z+IP+gnpv/guk/wDj9H2fxB/0E9N/8F0n/wAfo5V3/P8AyDnl/K/w/wAzVorK+z+IP+gnpv8A4LpP/j9H2fxB/wBBPTf/AAXSf/H6OVd/z/yDnl/K/wAP8zVoJwCayvs/iD/oJ6b/AOC6T/4/R9n8Qf8AQT03/wAF0n/x+hxX8y/H/IOeX8r/AA/zGeF/FOk+MNBi1fQrkT20hKsDw8Tjqjjsw9PoRkEGneH/ABNpXim2urnQ7kXdtbXL2pnT7juoG7ae45xnoccZGCeG1n4Oy6pqeqXlp4jk0YazGI9Tt9LtTFFec5JdTI2GPQlSpILZ+82ew0vQ9S0TS7fTdJudJtLO2QRwwx6bIFQD/tv+OepPJp8sd7/n/kJzlfSL/D/P+vnpv0yP78v+9/QVm/Z/EH/QT03/AMF0n/x+kFrr6liNT035jk/8S6T0x/z39qXKu/5/5D55fyv8P8zWorK+z+IP+gnpv/guk/8Aj9H2fxB/0E9N/wDBdJ/8fo5V3/P/ACDnl/K/w/zNWisr7P4g/wCgnpv/AILpP/j9H2fxB/0E9N/8F0n/AMfo5V3/AD/yDnl/K/w/zNWmSffi/wB7+hrN+z+IP+gnpv8A4LpP/j9IbXX2Kk6npvynI/4l0npj/nv70cq7/n/kHPL+V/h/ma1c/wCMdb1HQ9LtptHtYrq5muliEMoPzghiQMH7x24HX6Vb+z+IP+gnpv8A4LpP/j9U9Q0TWdSa0M+q2Km0uFuE2ae4yyggA5m6c0nFdJL8f8g53/K/w/zFTxMl5NoEmmGOS01VpNzMDuULGWwOeCCMHOe9O0vVtUn8Vahpmp29nDFBbxTQ/Z5GkYhiw+ZiF/u9AOPU1mW/gvUbXVlvrfV7VNty90luLBvLWR02OQPNzg9cZ61oR6HrMWtz6ouq2PnzwJAynT32hVLEEDzs5+Y96rljff8AP/IXPK3wv8O/r2Hzalqll4jsLW6NnNbag8qJHDGwkhCqWDFixDDjB+VcFhye8F5fa9Y63plm15p1z9tnIaNLCRGSJRl23ecRxwOnVhTX8Maj/aSaha3+m2d0JPMlkttNdDccEFZP33zjnPPIPIIqX+w9Z/tz+1W1axacW/2dFOnvsRd244HndSQMn/ZFJRWmv5/5A5y191/h/mO8U67No0mmJFd2Nkl5cNFJc3yFo4wI2YH76dSoHXvWvp0ks2nwyzXVvdtIu4T2qFI3B5BUbm4xjuc1T+z6/wD9BPTf/BdJ/wDH6x4PB+o29h9jj1iJIFmkmRYYriHZvbcVHl3C/KM8A5xRyruvx/yHzy/lf4f5l/XNW1TTdV0uO3t7M2N1dpbyyySMZfmDHhAAB06lj9Kk8S32p6ZptxqFjJZLBaQmV47iNmaYjnaCGATpgHDZJ6cc1r3QdYvlshLq1kBZTpPHixkJLKCBuJmJI5+vvRqXh3UNWCm9utJaZFIiuBpjiWEnuj+dlT3yKXKrfF+f+Qc7v8L/AA/zNsy3EunCW2jRZ3jDKkxICkjocDPFZWn6teRa5e6ZrE1pL9mtkuvtMEbQqqsWBVlZmwRtznPQ9OKkt7LxBBbRxNrFhMY0CmSTT3LPgdTiYcmse48GarcaTe2T67bhr+US3N0NPJllwQQpzKV24AXbjGOO5puKvo1+P+QlOVtYv8P8y/4d8Q3WtavqUU1ukFrCkUtrlSJGR92GfJ77QQMDAODzUvivWptEsrOSC4tLYXF2kDz3ilo4lIYliAy+nrWVaeD9etr+6upvFQuXu4limD2AjyFztwYnRlIyeQR1rVsdJ1rT4DFBq1q6lt2bi2uJmz/vPcE49s4ocY/zfn/kCnL+V/h/mWbaXUbvRkks9R026mlbKXcUDeTs9QgkJY8Y++Oue2DDoOr3Oo2Qa7SHzUvJbVpIQQkuzd86gk4BK9MnHPNULfwpewWt5ayXelXNrd3DXD29xpbPGrHBIC+dgDIz9Sasabout6XDJDbaxZtC0heOKSxkZYRgDYn77hRjgds8cYFHKn9r8/LyHztfZf4efmWbDxVpOo+J9T8PQXIGqaZsae3fhijorB19V+YAnsevUZdF4m0qfxZN4bt7lZdTt7b7VPEnPkoSAoY9mO7IHXHJxkZ5vxN8PLzxLqun6u2tQaZrGnN/o2pafYskyr3jO6VlZDk/KwI5PqczeEfAl34M0+a30vU7Oea6lM93e3di8lxdSEk7pH84ZPPoB+ZoUV1f5/5A5y6Rf4f5/wBfLXtKYf8Aj4T/AHW/mKzfs/iD/oJ6b/4LpP8A4/SfZdfLhv7T03IBH/IOk/8Aj/tRyrv+f+Qc8v5X+H+ZrUVlfZ/EH/QT03/wXSf/AB+j7P4g/wCgnpv/AILpP/j9HKu/5/5Bzy/lf4f5mrRWV9n8Qf8AQT03/wAF0n/x+j7P4g/6Cem/+C6T/wCP0cq7/n/kHPL+V/h/matUrj/Xt+H8qr/Z/EH/AEE9N/8ABdJ/8fqN7DXXYsdU07J9NOf/AOPUcq7/AJ/5Bzy/lf4f5liqum/8jVqP/Xla/wDoc9H9m65/0FNP/wDBc/8A8eqfS9Lu7TULq8vruG4kniiiAhtzEFCFz3dsk+YfTpTVknr/AFcluUpR91/h2fmalFFFZmwUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQB//9k=', '58', '2016-06-27 14:35:33.35', '2016-06-27 17:36:49.632', '0');
INSERT INTO "public"."info" VALUES ('61', '2342', '4234', '2', '2344', '', '58', '2016-06-27 17:46:33.093', '2016-06-27 17:46:33.093', '1');

-- ----------------------------
-- Table structure for info_type
-- ----------------------------
DROP TABLE IF EXISTS "public"."info_type";
CREATE TABLE "public"."info_type" (
"id" int8 DEFAULT nextval('info_type_seq'::regclass) NOT NULL,
"name" varchar(255) COLLATE "default"
)
WITH (OIDS=FALSE)

;

-- ----------------------------
-- Records of info_type
-- ----------------------------
INSERT INTO "public"."info_type" VALUES ('2', '活动风采');

-- ----------------------------
-- Table structure for security_role
-- ----------------------------
DROP TABLE IF EXISTS "public"."security_role";
CREATE TABLE "public"."security_role" (
"id" int8 DEFAULT nextval('security_role_seq'::regclass) NOT NULL,
"checked" int4 DEFAULT 0,
"sort" int4 DEFAULT 0,
"name" varchar(255) COLLATE "default",
"root_orinner" int4 DEFAULT 0,
"isadmin" int4 DEFAULT 0
)
WITH (OIDS=FALSE)

;

-- ----------------------------
-- Records of security_role
-- ----------------------------
INSERT INTO "public"."security_role" VALUES ('21', '1', '0', '系统管理', '0', '1');
INSERT INTO "public"."security_role" VALUES ('26', '1', '6', '测试员', '1', '0');
INSERT INTO "public"."security_role" VALUES ('27', '1', '5', '管理员', '0', '0');

-- ----------------------------
-- Table structure for security_role_user_permission
-- ----------------------------
DROP TABLE IF EXISTS "public"."security_role_user_permission";
CREATE TABLE "public"."security_role_user_permission" (
"security_role_id" int8 NOT NULL,
"user_permission_id" int8 NOT NULL
)
WITH (OIDS=FALSE)

;

-- ----------------------------
-- Records of security_role_user_permission
-- ----------------------------
INSERT INTO "public"."security_role_user_permission" VALUES ('27', '70');
INSERT INTO "public"."security_role_user_permission" VALUES ('27', '1029');

-- ----------------------------
-- Table structure for user_permission
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_permission";
CREATE TABLE "public"."user_permission" (
"id" int8 DEFAULT nextval('user_permission_seq'::regclass) NOT NULL,
"pid_id" int8,
"checked" int4 DEFAULT 0,
"sort" int4 DEFAULT 0,
"icon_class" varchar(255) COLLATE "default",
"name" varchar(255) COLLATE "default",
"value" varchar(255) COLLATE "default",
"ismenu" int4 DEFAULT 0
)
WITH (OIDS=FALSE)

;

-- ----------------------------
-- Records of user_permission
-- ----------------------------
INSERT INTO "public"."user_permission" VALUES ('70', null, '1', '3', 'icon-user', '用户管理', 'authorisedUser_html', '1');
INSERT INTO "public"."user_permission" VALUES ('111', '131', '0', '6', 'icon-hand-right', '菜单权限', 'userPermission_html', '1');
INSERT INTO "public"."user_permission" VALUES ('131', null, '0', '5', 'icon-desktop', '系统设置', '', '1');
INSERT INTO "public"."user_permission" VALUES ('1029', null, '1', '4', 'icon-hand-right', '角色管理', 'securityRole_html', '1');
INSERT INTO "public"."user_permission" VALUES ('1049', '131', '0', '7', 'icon-hand-right', '信息类型', 'infoType_html', '1');
INSERT INTO "public"."user_permission" VALUES ('1069', null, '1', '0', 'icon-hand-right', '信息发布', 'info_html', '1');
INSERT INTO "public"."user_permission" VALUES ('1089', null, '1', '1', 'icon-hand-right', '基金管理', 'fund_html', '1');
INSERT INTO "public"."user_permission" VALUES ('1090', '131', '0', '8', 'icon-hand-right', '基金类型', 'fundType_html', '1');
INSERT INTO "public"."user_permission" VALUES ('1109', '131', '0', '9', 'icon-hand-right', '广告类型', 'advertType_html', '1');
INSERT INTO "public"."user_permission" VALUES ('1129', null, '1', '2', 'icon-hand-right', '广告设置', 'advertSet_html', '1');

-- ----------------------------
-- Alter Sequences Owned By 
-- ----------------------------
ALTER SEQUENCE "public"."authorised_user_seq" OWNED BY "authorised_user"."id";

-- ----------------------------
-- Uniques structure for table advert
-- ----------------------------
ALTER TABLE "public"."advert" ADD UNIQUE ("code");

-- ----------------------------
-- Primary Key structure for table advert
-- ----------------------------
ALTER TABLE "public"."advert" ADD PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table authorised_user
-- ----------------------------
ALTER TABLE "public"."authorised_user" ADD PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table authorised_user_security_role
-- ----------------------------
ALTER TABLE "public"."authorised_user_security_role" ADD PRIMARY KEY ("authorised_user_id", "security_role_id");

-- ----------------------------
-- Indexes structure for table fund
-- ----------------------------
CREATE INDEX "ix_fund_fundtype_1" ON "public"."fund" USING btree ("fund_type_id");
CREATE INDEX "ix_fund_info_2" ON "public"."fund" USING btree ("info_id");
CREATE INDEX "ix_fund_user_3" ON "public"."fund" USING btree ("user_id");

-- ----------------------------
-- Primary Key structure for table fund
-- ----------------------------
ALTER TABLE "public"."fund" ADD PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table fund_type
-- ----------------------------
ALTER TABLE "public"."fund_type" ADD PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table info
-- ----------------------------
CREATE INDEX "ix_info_infotype_1" ON "public"."info" USING btree ("info_type_id");
CREATE INDEX "ix_info_user_2" ON "public"."info" USING btree ("user_id");

-- ----------------------------
-- Primary Key structure for table info
-- ----------------------------
ALTER TABLE "public"."info" ADD PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table info_type
-- ----------------------------
ALTER TABLE "public"."info_type" ADD PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table security_role
-- ----------------------------
ALTER TABLE "public"."security_role" ADD PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table security_role_user_permission
-- ----------------------------
ALTER TABLE "public"."security_role_user_permission" ADD PRIMARY KEY ("security_role_id", "user_permission_id");

-- ----------------------------
-- Indexes structure for table user_permission
-- ----------------------------
CREATE INDEX "ix_user_permission_pid_17" ON "public"."user_permission" USING btree ("pid_id");

-- ----------------------------
-- Primary Key structure for table user_permission
-- ----------------------------
ALTER TABLE "public"."user_permission" ADD PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Key structure for table "public"."authorised_user_security_role"
-- ----------------------------
ALTER TABLE "public"."authorised_user_security_role" ADD FOREIGN KEY ("security_role_id") REFERENCES "public"."security_role" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."authorised_user_security_role" ADD FOREIGN KEY ("authorised_user_id") REFERENCES "public"."authorised_user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Key structure for table "public"."fund"
-- ----------------------------
ALTER TABLE "public"."fund" ADD FOREIGN KEY ("fund_type_id") REFERENCES "public"."fund_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."fund" ADD FOREIGN KEY ("info_id") REFERENCES "public"."info" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."fund" ADD FOREIGN KEY ("user_id") REFERENCES "public"."authorised_user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Key structure for table "public"."info"
-- ----------------------------
ALTER TABLE "public"."info" ADD FOREIGN KEY ("user_id") REFERENCES "public"."authorised_user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."info" ADD FOREIGN KEY ("info_type_id") REFERENCES "public"."info_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Key structure for table "public"."security_role_user_permission"
-- ----------------------------
ALTER TABLE "public"."security_role_user_permission" ADD FOREIGN KEY ("user_permission_id") REFERENCES "public"."user_permission" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."security_role_user_permission" ADD FOREIGN KEY ("security_role_id") REFERENCES "public"."security_role" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
